from sympy import *
from sympy.printing.c import C99CodePrinter
import pathlib

import jerk_block
import polar_spherical
import azel
import mpc
import msc

"""
Writes the generated inline headers in lib/jerk/generated from the sympy models.
Run from any directory: python model/codegen.py
"""

output_path = pathlib.Path(__file__).parent.parent / "lib" / "jerk" / "generated"

class Printer(C99CodePrinter):
    def _print_Pow(self, expr):
        base, exp = expr.base, expr.exp
        if exp.is_Integer and 0 < exp <= 8:
            return "(" + "*".join(["(" + self._print(base) + ")"] * int(exp)) + ")"
        if exp.is_Integer and -8 <= exp < 0:
            return "(1.0/(" + self._print(Pow(base, -exp)) + "))"
        if exp == Rational(1, 2):
            return "sqrt(" + self._print(base) + ")"
        if exp == Rational(-1, 2):
            return "(1.0/sqrt(" + self._print(base) + "))"
        return "pow(" + self._print(base) + ", " + self._print(exp) + ")"

printer = Printer()

def body(inputs, outputs, scalar):
    """inputs: list of (symbol, c expression); outputs: list of (c lvalue, sympy expression)."""
    used = set().union(*[e.free_symbols for _, e in outputs])
    lines = ["        const " + scalar + " " + str(s) + " = " + c + ";" for s, c in inputs if s in used]
    temps, reduced = cse([e for _, e in outputs], symbols=numbered_symbols("t"), optimizations="basic")
    for t, e in temps:
        lines.append("        const " + scalar + " " + str(t) + " = " + printer.doprint(e) + ";")
    for (lhs, _), e in zip(outputs, reduced):
        lines.append("        " + lhs + " = " + printer.doprint(e) + ";")
    return "\n".join(lines)

def function(signature, inputs, outputs, scalar="double", template=False):
    head = ("    template <typename S>\n" if template else "") + "    inline " + signature + "\n    {\n"
    return head + body(inputs, outputs, scalar) + "\n    }\n"

def header(name, source, functions):
    guard = "KAEPEK_GENERATED_" + name.upper() + "_H"
    text = "/*\n * Generated by model/codegen.py from model/" + source + ". Do not edit.\n */\n\n"
    text += "#ifndef " + guard + "\n#define " + guard + "\n\n#include <math.h>\n\nnamespace kaepek\n{\n"
    text += "\n".join(functions)
    text += "}\n\n#endif\n"
    (output_path / (name + ".hpp")).write_text(text)

def matrix_outputs(name, M):
    return [(name + "[" + str(i) + "][" + str(k) + "]", M[i, k]) for i in range(M.rows) for k in range(M.cols)]

def vector_outputs(name, V):
    return [(name + "[" + str(i) + "]", V[i]) for i in range(len(V))]

def indexed(symbols_list, name):
    return [(s, name + "[" + str(i) + "]") for i, s in enumerate(symbols_list)]

def jerk_block_header():
    T, alpha, var_x, var_j = jerk_block.T, jerk_block.alpha, jerk_block.var_x, jerk_block.var_j
    return [
        function("void jerk_transition_small(double T, double F[4][4])", [], matrix_outputs("F", jerk_block.F_small())),
        function("void jerk_process_noise_small(double T, double Q[4][4])", [], matrix_outputs("Q", jerk_block.Q_small())),
        function("void jerk_transition_exact(double T, double alpha, double F[4][4])", [], matrix_outputs("F", jerk_block.F_exact())),
        function("void jerk_process_noise_exact(double T, double alpha, double Q[4][4])", [], matrix_outputs("Q", jerk_block.Q_exact())),
        function("void jerk_initial_covariance_small(double T, double var_x, double var_j, double P[4][4])", [], matrix_outputs("P", jerk_block.initial_covariance_small())),
    ]

def polar_spherical_header():
    return [
        function("void polar_position(double r, double az, double M[2])", [], vector_outputs("M", polar_spherical.polar_position())),
        function("void polar_covariance(double r, double az, double var_r, double var_az, double R[2][2])", [], matrix_outputs("R", polar_spherical.polar_covariance())),
        function("void spherical_position(double r, double az, double el, double M[3])", [], vector_outputs("M", polar_spherical.spherical_position())),
        function("void spherical_covariance(double r, double az, double el, double var_r, double var_az, double var_el, double R[3][3])", [], matrix_outputs("R", polar_spherical.spherical_covariance())),
    ]

def azel_header():
    state = list(azel.u) + list(azel.w) + list(azel.a) + list(azel.j)
    basis = list(azel.b1) + list(azel.b2)
    return [
        function("void azel_dynamics(const S x[12], double alpha, S dx[12])", indexed(state, "x"), vector_outputs("dx", azel.dynamics()), "S", True),
        function("void azel_basis_rate(const S x[12], const S b[6], S db[6])", indexed(state, "x") + indexed(basis, "b"), vector_outputs("db", azel.basis_rate()), "S", True),
        function("void azel_error_dynamics(const double x[12], const double b[6], double alpha, double A[8][8])", indexed(state, "x") + indexed(basis, "b"), matrix_outputs("A", azel.error_dynamics())),
    ]

def mpc_header():
    y = [mpc.beta, mpc.bd, mpc.bdd, mpc.bddd, mpc.l1, mpc.l2, mpc.l3]
    return [
        function("void mpc_to_xi(const S y[7], S xi[8])", indexed(y, "y"), vector_outputs("xi", mpc.to_xi()), "S", True),
        function("void mpc_from_xi(const S xi[8], S y[8])", indexed(list(mpc.xi), "xi"), vector_outputs("y", mpc.from_xi()), "S", True),
    ]

def msc_header():
    state = list(msc.u) + list(msc.w) + list(msc.a) + list(msc.j)
    return [
        function("void msc_to_xi(const S x[12], const S lam[3], S xi[12])", indexed(state, "x") + indexed([msc.l1, msc.l2, msc.l3], "lam"), vector_outputs("xi", msc.to_xi()), "S", True),
        function("void msc_from_xi(const S xi[12], S y[16])", indexed(list(msc.xi), "xi"), vector_outputs("y", msc.from_xi()), "S", True),
    ]

if __name__ == "__main__":
    output_path.mkdir(parents=True, exist_ok=True)
    header("jerk_block", "jerk_block.py", jerk_block_header())
    header("polar_spherical", "polar_spherical.py", polar_spherical_header())
    header("azel", "azel.py", azel_header())
    header("mpc", "mpc.py", mpc_header())
    header("msc", "msc.py", msc_header())
